### ISSUE TITLE
 (t = o[i]) && ~t.className.indexOf(cls) && rs.push(t);

### ISSUE THREAD

**Issue by objectivezhou** [hanzichi/hanzichi.github.io#1]
求教~t是什么意思？

**Comment by hanzichi** [comment]
`~` 是位运算取反的意思，`t.className.indexOf(cls) !== -1` 可以简写成 ` ~t.className.indexOf(cls)`，因为只有 -1 取反为 0， 是 false，其他情况都会是 true
